### PR TITLE
Twitter Locations

### PR DESCRIPTION
**Pull request by yuxshao**
- `Location`s augmented with `bbox_width`, `bbox_height` for bounding boxes
- `Tweet` constructor takes in `location`
- `twitter_search` automatically converts `place` from Twitter into `Location`, and fills `line1`, `street_address`, `city`, and bounding box fields according to `Location` data. Note that it fills `street_address` with the Twitter place's id for locations from Twitter. Would it be a good idea to change the field name to just `id` or something?

### CODE REVIEW

**Comment by teffland** [comment]
I don't know if using twitter's place id for the `street_address` is a good idea.  My initial thoughts about using street address is that a location should be uniquely identified by essentially the same way the post office would identify an address.  We may need to rethink how we key this class. 

After all we need to be able to handle locations other than from Twitter, but maybe adding an optional field to store the twitter `place_id` in a way that locations with the same `place_id` would be matched in the database.  One possible way to do this is to drop the `street_address` key and revert back to the correct form which would be the keyset {`line1`, `line2`, `line3`, `city`, `state`, `zip`} but then extend it to accommodate these new granularity features by adding the `bbox_width` and `bbox_height` to the key. We don't want to add lat/lons to the key because this opens up the door to an over parameterized key where we have the same street address but differing / null lat lons.  Instead we could always reverse geocode the lat/lons to the street address and then express the granularity of that address via the added box dimension attributes.  What do you think?

**Comment by yuxshao** [comment]
I think with the addition of Twitter locations, the Location model is trying to fit two classes of regions into one: a specific address/point on the map, and a large general area. Specifically the location data that we get would be either
1. A specific business location with detailed addresses from Yelp
2. A large general region (e.g. Manhattan, NY) with a bounding box from Twitter
3. A specific point (e.g. Sweetgreen) with coordinates but little address info from Twitter

I originally had the idea of using the place's `full_name` but multiple locations could have the same `full_name` for specific places like Sweetgreen. It'd work well for large regions like "Manhattan, NY" though. If we want to keep the `street_address` identifier as it is I think that yeah, ideally it would be a reverse-geocoded address in case 3 or just the `full_name` in case 2. This would keep it unique and also representing around the same data as it's been doing for Yelp locations.

But would it be feasible to immediately reverse-geocode the coordinates as we retrieve tweets? Or would it be okay to store possibly redundant Locations (with an overparameterized key) and later run through all the recently added locations and combine the ones that point to the same thing?

**Comment by yuxshao** [comment]
Actually, if we want _just_ a key for our Location, I do think the place id may be our best bet, since it's generally unique and covers the classes of Locations we want, though occasionally places might be repeated (like New York, NY and New York, US).

I think this is a good candidate because Twitter's set of places is pretty comprehensive, so even if we end up having different data sources it's probably easiest to match locations from other places with a Twitter place id. 

All the Yelp business locations are probably places on Twitter too, so we can do a geo search to find them since we have their coordinates and names. 

What do you think about this? Is there something else to consider in making the key? What are data sources are we looking at, and what possible locations do you think might not fit with a Twitter place?

**Comment by teffland** [comment]
I would think that reverse geocoding on the spot is more doable that querying the place on twitter for an id -- given correct coordinates, reverse geocodes are almost always possible I would think. Plus this saves us on Twitter API calls.

I don't think it's a good idea to restrict our places to Twitter's. Say a new Yelp business is in tomorrow's feed.  We would have to assume that Twitter has this location, in the form of a place.  I just checked and to query Twitter for a place requires the lat/lon, but this is usually not given by Yelp -- so we would have to geocode the address (which often doesn't work), then query twitter.  

However if we just convert twitter places to our own data type, then we don't need to keep the id, or necessarily know the lat/lon.  To me it makes more sense to conform Twitters places to our `Location` than to conform all of our `Location`s to Twitter's places.

We want our `Location`s to be general, in the case of additional data sources, such as extracting locations from free text or other sources like TripAdvisor.

As you said, we are trying to address two scenarios with one model, but I think it's important we keep them together.

In the case of Yelp (case 1), we always have a (mostly) complete text address, but not usually the geocode.  If the address is incomplete, it may not be possible to geocode it, but that's ok since we know from the start that our reviews all come from NYC, so we don't need to compare overlaps of these Locations.  Here we would have the key `{line1, line2, line3, city, state, zip, bbox_w=NULL, bbox_h=NULL}`

In the case of Twitter (case 2), we would be dealing with places, which always have geocodes, but often incomplete addresses (because they're too coarse granularity). In this situation, we need the addresses to be numerical so we can do bounding box overlaps. In the case of a general "New York, NY" we would have the key `{line1=NULL, line2=NULL, line3=NULL, city, state, zip=NULL, bbox_w, bbox_h}`.  Note that this we still suffer from ambiguous places like "New York, NY" and "New York, US", however, my expectation is that these actually represent two different places , the city and the state.  Either way these would still have different `place_id`s if Twitter is able to store them separately, so using that as a key wouldn't help.

In the specific coordinate case of Twitter (case 3), (assuming the address is incomplete) we should be able to always reverse geocode a coordinate to an address. 

But are you sure the address info is incomplete on these? If this is true what I said above should apply.  If it isn't we have even less to worry about.

Assuming an incomplete address that is geocoded, we have the key `{line1, line2, line3, city, state, zip, bbox_w=0, bbox_h=0}`

I think this is a good general format for dealing with locations from multiple sources in many granularities with as little duplicates as possible.  What do you think?

**Comment by yuxshao** [comment]
Just a few things -- not sure if they really matter though: place IDs (and most of the place info) are included with tweets and Twitter's locations are taken from Foursquare, which is known for its comprehensiveness, much more so than TripAdvisor or Yelp. And, why is geocoding that much harder than the reverse? If we're given an address isn't it actually more likely that it corresponds to a valid lat/lon than the reverse?

Otherwise, if reverse-geocoding as we receive tweets is doable and easier than regular geocoding then I think that key system is practically fine. Regardless of how complete a given source's place database is, it's not exactly right to base our locations off a particular source even if that source's locations are all-encompassing. What kind of library/source do you think would be good for address-level reverse-geocoding? Google Maps (2500 a day)?

[This system also still doesn't feel exactly right to me though, since we're relying on that rarely will city non-specific regions' bounding boxes be the same size, instead of something that is inherently unique within these classes of locations. Since we're really just focusing on NYC though it shouldn't be a problem] 

About the incompleteness of address fields, I tested with some tweets against `geo/id/:place_id` before my last post and in general, the place returned has no address field usually, or sometimes a single-line street address. On the `geo/search` API page there's an example of a street address returned, but when I tested with Sweetgreen there was nothing, even though when I was adding the location to the test post, a street address appeared. I think the street address is retrieved from Foursquare during posts but not during searches.

So just a recap: change the key to multiple fields. Keep Yelp locations unchanged. Twitter locations with non-zero bbox_w/h require no reverse-geocoding; instead fields are filled in directly from the Place. Twitter specific coordinates will be re-geoed to an address with lines that fill in the remaining Location fields.

**Comment by teffland** [comment]
> [I think that should work for pretty much all cases, but it still doesn't feel exactly right, since we're relying on that rarely will city non-specific regions' bounding boxes be the same size, instead of something that is inherently unique within these classes of locations. Since we're really just focusing on NYC though it shouldn't be a problem]

I don't understand what you mean by this.  Can you please elaborate?

I've used the OpenStreet maps api already in the code (no api limits).  It's at the bottom of `yelp_fast.py`.

Ok so we need to confirm/debunk a couple of things before moving forward then:
- [ ] In case 3, how successful is reverse geocoding a coordinate pair: take a sample of lat/lons from tweets and try reverse geocoding them to get a % success rate
- [ ] In case 3, how uncommon is the single `street_address` field, because if it's even remotely common we should be able to just parse it with a regex and combine it with the `contained_in` metadata to infer the total address
- [ ] I'm slightly confused by your Sweetgreen example. Do you mean you used it's lat/lon and no street address came back? We need to clarify how to retrieve the address in this situation

Given answers to these, then:

> So just a recap: change the key to multiple fields. Keep Yelp locations unchanged. 

Yup, bounding boxes will be NULL for specific addresses.  If we have a lat/lon then the bbox should be set to 0.

In general we cannot have a filled in bbox dimension without a center point.  This can be added as an [Integrity Check Constraint](http://docs.sqlalchemy.org/en/latest/core/constraints.html#check-constraint) to the `Location` table
where we have `(bbox_w AND bbox_h AND lat AND lon) OR NOT (bbox_w OR bbox_h OR lat OR lon)`

(Basically either we can quantitatively compare locations or we can't, no in between)

> Twitter locations with non-zero bbox_w/h require no reverse-geocoding; instead fields are filled in directly from the Place. 

This seems like the only option since the locations are not at the specific-street address granularity

> Twitter specific coordinates will be re-geoed to an address with lines that fill in the remaining Location fields.

Yes, if we cannot infer the location from metadata passed with the `Place` by using `street_address` and `contained_in`

**Comment by yuxshao** [comment]
I'm saying that I don't think an address + bbox dimensions exactly make a location identifier. If two regions in a city have the same dimensions there'd be a problem, but to someone just reviewing the code such a choice of key would be hard to explain. I imagine the collision case is super rare though so for all practical purposes we shouldn't have to worry about it.

In response to your 3 points:
- For specific points extracted from Twitter places, reverse-geocoding can be inaccurate ([example: Sweetgreen near Lerner](http://nominatim.openstreetmap.org/reverse?lat=40.806764&lon=-73.964705)). Another option might be to reverse-geocoding a coordinate pair + the name of the location looks more promising ([example](https://www.openstreetmap.org/search?query=Sweetgreen [40.806764%2C -73.964705])) but OpenStreetMap's sort of deficient in its restaurant database (it doesn't have the other Sweetgreen downtown for example). I'm not too confident in either method. Testing might be difficult as very few tweets location-tag, with only a small fraction of those having tags more specific than, say, Manhattan, NY. It'd be better to get a sample of places, but getting such a sample is its own challenge. 
- I'll look more into how common `street_address` is. If it's there yeah we can pretty consistently reconstruct the whole address if we have a street address line from Twitter.
- About the Sweetgreen example: I made a test tweet with Sweetgreen as my location. In the post dialog box a street address was displayed along with the Sweetgreen location. However, there's no street address in the response from `geo/id/:place_id` if I use the same Sweetgreen ID, which is weird because [an address is also given in a normal web search](https://twitter.com/search?q=place%3A07d9e1b8c7887000). It would be ideal if we could get the address in our API call but that might require dealing with Foursquare.

**Comment by teffland** [comment]
Ah I get what you're suggesting. It seems odd because it technically crosses over the two types of locations, but the case you mention would not happen as we need to have a center lat/lon as part of the check constraint so that the bounding boxes aren't translation ambiguous. Two different regions in the same city with the same dimensions would still have different names, otherwise they'd be the same region, so then there wouldn't be ambiguity. Either way I think this does uniquely identify a location.

After some digging, I think we may be able to solve bullets 1 and 3 simultaneously.  Why not just use FourSquare as our geocode/reverse-geocode service.  The API allows up to 5000 hits per hour, the database is super accurate, and it's the same database that Twitter uses for it's locations

**Comment by yuxshao** [comment]
Sorry, I don't really follow your explanation about key uniqueness. I get that practically the key system wouldn't have any collisions but if a city had two equal-sized regions centred at different points, wouldn't they have the same key? line1 = line2 = line3 = zip = null, same city, same bbox_w/h, same state, and the constraint doesn't change anything since centres for both regions exist.

Okay, if we're using Foursquare for specific locations we're limiting our set of locations to a subset of Twitter's places anyway, right? Why don't we then use Twitter's place id as the key? I think by far Twitter places is far more comprehensive than any other site's--and also very organized. Rate limits for finding a place for a business should also be insignificant since there aren't that many Yelp businesses compared to reviews/tweets.

**Comment by teffland** [comment]
True, technically you could put in some sort of adversarial set of boxes that have a key collision, but practically speaking, we are never just given an empty(ish) address with only the width and height of the bounding box.  We are given the 4 corners, which uniquely defines the box. In this case a collision is impossible. So yes the key isn't theoretically perfect, but it will work in practice. I can't think of a better way to key this class if we are doing the keys ourselves.

I see what you mean about using the places instead.  It does seem like it could save us a lot of this headache. If you feel that this is the best direction to go and won't interfere with obtaining location data for other data sources, I'm ok with it.  I just have reservations about committing our model to conform to Twitter's.  To make this switch though we need to make sure we thoroughly consider possible drawbacks.

Some things I'm curious about: 

How do you query places given the string of an address? (Doesn't it require lat/lons?)

How would you ensure the mapped place is the correct and unique place for the Yelp businesses?  (Doesn't it return multiple candidates?)

What do we do if we can't get the correct place from Twitter?  

And how do you think the `Location` model should be structured if we go this direction?

We should also consider Google Maps which allows up to 2,500 requests per day and Google Places which allows up to 150,000 per day

**Comment by yuxshao** [comment]
Ah, my bad. I had forgotten that Yelp doesn't always give geo coordinates, and Twitter's place API also hates giving specific locations in query responses. I got hung up on trying to get some ID that'd be representationally unique but yeah Twitter's place API is really a nightmare, even if we start with a place ID and just want to get other info. Thanks for those questions, haha

About the key uniqueness, sorry, I'm still confused. Again, I understand that for all practical purposes region dimensions are unique already (since they're floating-point) so the key works fine, but say we're given 2 districts from Twitter defined by corner coordinates [0,0]x[1,1] and [1,0]x[2,1] that are in the same city. This isn't nearly as extreme as the adversarial case you described with completely null addresses and just a null lat/lon centre, and this is what concerns me about keying case 2 locations with just the dimensions. Wouldn't they have the same key?

As I'm writing this some ideas pop in my mind:
- Other than what was said above I think that the key system you suggest would be best, and then use Foursquare (this [one](https://developer.foursquare.com/docs/venues/search)?) to fill in the missing fields from either a Twitter place (address) or the Yelp location (coords). 
- But if we do this, for reasons above I think it'd be good to include the coord centre in the key. If a Yelp Business comes with a coordinate we should override that with an authoritative Foursquare coordinate since it's generally more accurate and would remove duplicates between Twitter and Yelp (in case coordinates don't match slightly).

So to summarize:
- For Twitter specific points, get the address from Foursquare using the geo + name. This should always work since these points are exactly Foursquare locations (I think).
- Keep Twitter regions unchanged.
- For Yelp businesses, query the address on Foursquare to get an authoritative address and coordinate, and use those. In the rare case where Foursquare doesn't return a coordinate/address, use the Yelp coord/address if it exists.
- Location structure remains unchanged*
- Query Foursquare as we download Yelp businesses/tweets? Few tweets actually get location-tagged so hopefully we don't reach the limit too fast.

*After writing this, I thought: how about just keeping our current separate column to identify locations? Using a composite key suggests some cartesian product of items but we really want some union instead. If we make a separate column that is _either_ the street address for specific points (as we have now) or a bounding box/general name (`full_name`) for large regions, would that suffice? It clearly distinguishes our two types of locations, is easy to retrieve, and doesn't over/underspecify. (we discussed something similar earlier but we moved to `place_id` instead of `full_name` and hadn't considered Foursquare)

**Comment by teffland** [comment]
Ok cool, glad we're off of the `place_id`s haha.

Maybe the confusion here is we aren't thinking of the same formulation of granular places.  In my view, if the region is not a city the qualifying name would fill in `line1`, eg, "Manhattan, New York, NY" would have `line1="Manhattan"`.  So if two regions do in fact have the same bounding box dimensions, either they are different regions as qualified by the name, or they are the same, in which case we do want them to resolve to the same key.  Does this make sense? I am still struggling to see a situation where two regions are qualitatively different but have identical bounding box dimensions, given that they are qualified by the place name.

If we include the bbox center in the key, it will be over parameterized, we could have identical quantitative locations buts different qualitative addresses, or worse the same qualitative address with different lat/lons...

After looking at FourSquare a bit, the ToS denies us from saving their locations... So I think we should more seriously consider using Google.  The more appropriate API is [Google Places](http://gretarose.com/google-maps-vs-google-places-what-they-are-and-why-google-uses-both/) and we can hit that up to 150k times/day so no worries there.  Plus it should have a very complete record of businesses (and we could also potentially mine these reviews as well).

In your response to your summary, I think it is good but sub in Google Places instead of Foursquare.
- I see what you mean, but using one identifying string implictly does the cartesian product of all possible length(N) strings as a single character change makes it a new key, so really it does the same as the composite key.  I'm not against using the convenience column, but using only that and not separating the fields could lead to parsing ambiguities later, if we want to say display the addresses "New York, US" and "New York, NY".

**Comment by yuxshao** [comment]
I see. From the New York, NY example, I thought only specific points would have anything in the address fields, and that something like Manhattan would have `line1 = null` too since there's no street address line for such a general location. So `line1` is filled with any part of the location name more specific than the city? That clears things up for me; in that case I agree bbox centres are unnecessary. Sounds like a good key to me.

Hm... it looks like Google Places has a [similar, if not stricter policy](https://developers.google.com/maps/terms?csw=1#10-license-restrictions) on retention. Would that be a problem here? Speaking of which, Yelp _also_ has [something](https://www.yelp.com/developers/api_terms) but I'm guessing the partnership with DOHMH supersedes that. 

Edit: One thing we could do, if we plan on making Foursquare/Maps our decider on location info, is just have a job that updates locations once a month. This would definitely put us within Foursquare's retention policy (at least, [IV here](https://foursquare.com/legal/api/platformpolicy)), and also remove any sort of duplicates that result from slight address changes in Foursquare's database. Major changes like an actual restaurant move might pose a problem, though.

**Comment by yuxshao** [comment]
About moving forward with how to fill in the parts of the address and detect duplicates for Twitter's places, it looks like regions aren't classified very well either by Twitter. We could've theoretically distinguish between New York, NY and New York, USA without the bbox w/h as one of them would have a null city field, but Twitter says "[New York, NY](https://twitter.com/search?q=place%3A27485069891a7938)" and "New York, USA" are both administrative regions, while _Manhattan_, NY is a city, contained in a separate location called "[New York NY](https://twitter.com/search?q=place%3Ab6c2e04f1673337f)". So, Twitter's places have duplicates and not the best labels. 

But, if we're okay with disregarding any tweet outside NYC (even if it might be NYC-relevant), then there aren't that many cases to consider. For each location we get, we'll check for a bounding-box overlap. If there is none, we'll throw out the tweet. Once that's done, we look at the cases:
- Places that contain NYC, like United States, or NY State. Maybe a few of these places is duplicated in Twitter's Place database.
- Each borough. I did a quick search and they're unique in Twitter's Place DB, but labelled as cities.
- [Neighbourhoods](https://twitter.com/search?q=place%3A6497298c68c6fe28). I imagine these are much less likely to be duplicated, and also are very rarely used. They also seem to follow the format `[neighbourhood], [borough]`.
- POIs, but these are from Foursquare and are probably unique per place.

I can't think of a Twitter Place intersecting NYC but not either a superset/subset of NYC. Would there be any case like that? Or you think these cover them all? If so, I think a good way to move forward is to have some specific logic for each of these cases:
- We can have a check that automatically associates every Tweet with large location, like "New York, NY" or "New York NY" with a premade place representing the city, just because Twitter doesn't give much info about such a location (it'd only say "New York, NY" is the name of the Place, and that it's an administrative region). 
- We can do the same for each borough; "Manhattan, NY" goes straight to a Place already made with `line1 = 'Manhattan'`, `city = 'New York'`,, etc since the info on the Place itself is sort of wrong (labelled as a city). 
- Neighbourhood Place names can be converted to Locations with a bit of processing (splitting on the comma, or right before the borough name)
- POIs get reverse-geocoded and their Locations built from the address + coordinates from the Place. 
- Anything that doesn't line up (say, if there were a sub-neighbourhood like "East Harlem, Harlem") we can just put `full_name` with the location's `line1` and fill the coordinates appropriately. 

So there's a bit of hard-coded NYC-specific logic here, but I think putting it in some PlaceToLocation function would make this handling reasonably isolated. What do you think? Retrieve specific locations from Foursquare, and do some manual parsing of general regions after culling places outside of NYC, while having a periodic refresh.

**Comment by teffland** [comment]
Ok does Google have a similar refresh policy? because I would expect their places to be more complete and I'd rather use them than foursquare if we can.  

After some searching. It turns out that the way twitter is doing it is correct... technically speaking. New York is a county.  Manhattan (also called New York) is a city, and all of the other boroughs are other cities technically. For example, it's possible to have the same exact street address in Mahattan an Brooklyn with the only change being the city and zip.

As of now, yes, we won't be considering locations outside of NYC (but this should be just a False returned by our location comparison method) or using actual text to try and resolve the location (although we shouldn't totally shut the door on using that idea in the future -- it's just very noisy)

I don't think it's a good idea to restrict this to NYC specific logic.  In the future this software is planned to be used in monitoring other locales.

What is wrong with defining a function that just accepts two bounding boxes (or (2) can be a point) and calculates intercepts, feeding in (1) for our location of interest (a bounding box for all of the boroughs together -- or NY county?, we should clarify the jurisdiction of DOHMH) and another (2) for the tweet/user location/place we want to analyze? In this function either the tweet is a subset, superset or overlaps. 

I can't think of a specific overlap example, but that doesn't mean we shouldn't consider it as it's not hard.

**Comment by yuxshao** [comment]
Foursquare says that one "should try to keep data up to date and must delete all old data" while Google Places (same policy as maps) says the only use of caching must be for "improving the performance of your [Places] API Implementation due to network latency" which seems to bottleneck our usage. The Quora answer [here](https://www.quora.com/What-are-the-pros-and-cons-of-each-Places-API) reiterates and also gives an opinion on coverage between the two services. This is probably more of a concern for apps that say, store review/check-in data than something that geocodes, though, so I'll look into it some more.

Oh, I never knew that! But Wikipedia seems to be saying [something](https://en.wikipedia.org/wiki/List_of_counties_in_New_York#Five_boroughs_of_New_York_City) different, that rather, the _boroughs_ are coterminous with counties, not cities themselves. Is that still technically right?

I agree it's not hard to determine an intersection -- we can keep that general for sure -- but I'm not sure if we're talking about the same issue(?): I'm referring to after determining an intersection, when we make a Location object from the Place. In order to fit the Location model we have correctly (e.g., convert Twitter Place "Manhattan, NY" to a location with `line1 = Manhattan`, `line2 = ... = null`, `city = New York`, `state = NY`) we have to do something to get the correct parts of the Place in the right fields. Something that converts Places to Locations (for now, in NYC). Since Twitter's places for the boroughs and New York are labelled weirdly (also, we only get a single name and coords) and we're just focusing on NYC, it might be good to insert a specific code for handling these few cases. This wouldn't restrict the entire application to New York, since all of this processing would be in an extensible function that can later handle other areas too.

Are you saying that if Manhattan is really the city and New York a county, we don't need NYC-specific Place-To-Location method? That instead, we can e.g. look at the `contained_in` and infer the fields of our converted Location that way?

**Comment by teffland** [comment]
Ok, it looks like we'll have to go with foursquare then, as Google Places geocoding doesn't look great... and we don't want to limit ourselves to 2.5k per day.

I think I see what you mean now, but I think these issues kind of all revolve around what technically constitutes a region vs city... I believe that your last paragraph is what I'm saying. 

If we have a region with a name (say Morningside Heights) `contained_in` a `city` (say Manhattan) then we should just use that formulation.  If we have a name (say Manhattan) `contained_in` a `region` (say New York County) then we should fill in Manhattan as a `city` with no `line1`.  This logic would be indifferent to NYC specifically, but instead just defined consistently based on the responses twitter gives us.  

Does this work? I haven't seen much actual data so it's your call on what you think is the right move, but my intuition is to just come up with some consistent mapping using `full_name` and `containted_in` values to map to `Location` fields with the only hardcoded logic being how we use the metadata of `contained_in` to map the `full_name` and `contained_in` name

**Comment by yuxshao** [comment]
Yeah, I think that should work consistently across Twitter for the most part (e.g. Morningside Heights is a neighbourhood in Manhattan, a city, in New York NY, an admin region). Hopefully we don't get a new source that calls Manhattan a city, haha. I'll update the branch so:
- It uses the key you suggested and columns are updated
- Twitter search queries Foursquare for addresses when retrieving tweets with specific locations (that is, set up API, do some caching to avoid too many Foursquare calls)
- An extra job to query Foursquare and update business addresses/coords, after a Yelp download. 

Hope everything goes smoothly...

**Comment by teffland** [comment]
Sounds good, best of luck 8D

**Pull request closed without merging**
