### PR TITLE
Methods unit tests

### PR DESCRIPTION
**Pull request by kzeng10**
Some unit tests for the `yelp_classify` function, using the local toy.db. Also added click functionality to `generate_test_db` file to make it easier to use on the command line, and ability to redirect logging output to a file (especially useful for recording test results on TravisCI)

### CODE REVIEW

**Comment by yuxshao** [comment]
Hey Kevin, just a quick git note: it may be a good idea to rebase against master to pull in the newest changes made to master since you started your branch. You might have to resolve a few conflicts but this ends up with a cleaner version tree than resolving when merging with master.

Also, after reading through your code, I was wondering, would this work better as an integration test instead of a unit test? It looks like rather than testing the individual functionalities in `YelpClassify` (interfacing with `sklearn` and the database) it's more of verification that the whole classification system satisfies some general properties we want. What do you guys think?

**Comment by kzeng10** [comment]
@yuxshao yeah I was thinking that this would go more along the lines of an integration test given how it involves both models and methods. Either way, I intended to work on this portion to get myself familiar with how the classifiers work, since I'm currently looking into other supervised learning algorithms for information retrieval.

About the git note, I tried doing a rebase, but it was giving me some errors so I ended up merging master into this branch. Not sure if that accomplishes the same thing...

**Comment by kzeng10** [comment]
@yuxshao I tried merging in the most recent branch of master into this PR, and the Travis build is giving me errors related to test_documents. Can you take a look and see what's going on? I can't really tell myself.

**Comment by yuxshao** [comment]
@kzeng10 are you sure you merged into master? it looks to me like you merged into my twitter-location branch. i did some work there that may be conflicting. but in general, `rebase master` instead of merge when updating your own branch (whether local or on github) to pull in newest changes -- if there's an error from rebasing something's probably actually been done wrong, and forcing a merge won't help later down. lemme try reorganizing the git tree

other than that it looks like your changes to to `test_db.py` made some of my tests complain **edit** because the `test_db.py` functions now exit after being run, and so they can't be used in test setup i think?

in your tests, it looks like `doc.fp_pred` isn't being filled -- not sure what might be the cause. is a package installed locally but not on travis?

**Comment by yuxshao** [comment]
okay, for git: i went back and undid the merge with `twitter-location`, as well as the merges before. then, i did `git rebase master` and got a merge conflict in `generate_test_db.py`. i suspect that's there was a problem with merging for you earlier. after conflict resolution lal files are unchanged\* but the git tree is neat now. 

*i think the only changed files are the ones in `pipelines/models` (oops, sorry! -- i'm not sure if i can recover them easily on my system). i think it'd be a good idea to copy that folder out, then rename your local `unit-tests` to a backup and do a `git branch --unset-upstream` (so it's not connected to `origin/unit-tests` any more), then pull `unit-tests`, then replace that folder and make a commit to get everything back together.

other than that, i looked again through the travis error log and i think that the two difficulties with the tests are just those mentioned above: click exiting and travis not filling in the prediction columns?

**Comment by kzeng10** [comment]
At last! Turns out the root cause was adding in click to `test_db`. I wanted to do that to make the whole process of resetting `toy.db` a lot faster.

**Pull request merged**
